server:
  port: 8782
spring:
  application:
    name: cloud-dy-user
  cloud:
    nacos:
      discovery:
        server-addr: 47.110.77.37:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'