server:
  port: 8782
spring:
  application:
    name: cloud-dy-user
  cloud:
    nacos:
      discovery:
        server-addr: 47.110.77.37:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

xxl:
  job:
    executor:
      address:
      logpath: logs/xxl-job/jobhandler
      appname: cloud-dy-user-xxl-job-executor
      port: 9999
      logretentiondays: -1
      ip:
    admin:
      addresses: http://39.101.188.7:8780/xxl-job-admin
    accessToken: