server:
  port: 8099
spring:
  application:
    name: cloud-dy-admin
  cloud:
    nacos:
      discovery:
        server-addr: 47.114.63.164:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS