#server:
#  port: 8785
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:8066/TESTDB?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#    username: root
#    password: 123456
#    dbcp2:
#      max-wait-millis: 1000000000
#
#logging:
#  level:
#     com.cloud.dream.serveruser: debug
