spring:
  redisson:
    address: "redis://10.0.131.236:6379"
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    commandTimeout: 5000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle: 5
    database: 0
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
    timeout: 0